---

- include_tasks: remove.yml
  when: 
    - ansible_facts['distribution'] == "Debian" or
      ansible_facts['distribution'] == "Ubuntu" or
      ansible_facts['distribution'] == "OracleLinux" or
      ansible_facts['distribution'] == "RedHat" or
      ansible_facts['distribution'] == "CentOS"
  tags: 
    - remove_old_repo

- include_tasks: gpg.yml
  when: 
    - ansible_facts['distribution'] == "Debian" or
      ansible_facts['distribution'] == "Ubuntu"
  tags: 
    - add_gpg_repo
    - add_debian_repo
    - add_ubuntu_repo

- include_tasks: debian.yml
  when: 
    - ansible_facts['distribution'] == "Debian"
  tags:
    - add_debian_repo

- include_tasks: ubuntu.yml
  when:
    - ansible_facts['distribution'] == "Ubuntu"
  tags: 
    - add_ubuntu_repo

- include_tasks: oracle.yml
  when:
    - ansible_facts['distribution'] == "OracleLinux"
  tags: 
    - add_oracle_repo

- include_tasks: redhat.yml
  when:
    - ansible_facts['distribution'] == "RedHat"
  tags:
    - add_redhat_repo

- include_tasks: centos.yml
  when:
    - ansible_facts['distribution'] == "CentOS"
  tags:
    - add_centos_repo

- include_tasks: stable.yml
  when:
    - ansible_facts['distribution'] == "Debian" or
      ansible_facts['distribution'] == "Ubuntu" or
      ansible_facts['distribution'] == "OracleLinux" or
      ansible_facts['distribution'] == "RedHat" or
      ansible_facts['distribution'] == "CentOS"
  tags: 
    - add_stable_repo
    - add_debian_repo
    - add_ubuntu_repo
    - add_oracle_repo
    - add_redhat_repo
    - add_centos_repo