---

# CentOS 7 repositories
- name: Configure repo yum <|> CentOS 7
  ansible.builtin.yum_repository:
    name:        "{{ item.name | default(item, true) }}"
    description: "{{ item.description | default(item.name, true) | default(item, true) }}"
    baseurl:     "{{ item.baseurl | default(omit) }}"
    enabled:     "{{ item.enabled | default(1) }}"
    exclude:     "{{ item.exclude | default(omit) }}"
    gpgcheck:    "{{ item.gpgcheck | default(0) }}"
    gpgkey:      "{{ item.gpgkey | default(omit) }}"
    proxy:       "{{ item.proxy | default(omit) }}"
    state:       "{{ item.state | default('present') }}"
  loop: >-
    {{
      co7_base_repositories | default([]) 
      | union(co7_product_repositories | default([]))
      | union(co7_hosts_repositories | default([]))
    }}
  register: yum_register_co7_all_repo
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
    - co7_base_repositories is defined or
      co7_product_repositories is defined or
      co7_hosts_repositories is defined
  tags:
    - add_centos_repo