---

# Redhat 7 repositories
- name: Configure repo yum <|> RedHat 7
  ansible.builtin.yum_repository:
    name:        "{{ item.name | default(item, true) }}"
    description: "{{ item.description | default(item.name, true) | default(item, true) }}"
    baseurl:     "{{ item.baseurl | default(omit) }}"
    enabled:     "{{ item.enabled | default(1) }}"
    exclude:     "{{ item.exclude | default(omit) }}"
    gpgcheck:    "{{ item.gpgcheck | default(0) }}"
    gpgkey:      "{{ item.gpgkey | default(omit) }}"
    proxy:       "{{ item.proxy | default(omit) }}"
    state:       "{{ item.state | default('present') }}"
  loop: >-
    {{
      rh7_base_repositories | default([]) 
      | union(rh7_product_repositories | default([]))
      | union(rh7_hosts_repositories | default([]))
    }}
  register: yum_register_rh7_all_repo
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "7"
    - rh7_base_repositories is defined or
      rh7_product_repositories is defined or
      rh7_hosts_repositories is defined
  tags:
    - add_redhat_repo

# Redhat 8 repositories
- name: Configure repo yum <|> RedHat 8
  ansible.builtin.yum_repository:
    name:        "{{ item.name | default(item, true) }}"
    description: "{{ item.description | default(item.name, true) | default(item, true) }}"
    baseurl:     "{{ item.baseurl | default(omit) }}"
    enabled:     "{{ item.enabled | default(1) }}"
    exclude:     "{{ item.exclude | default(omit) }}"
    gpgcheck:    "{{ item.gpgcheck | default(0) }}"
    gpgkey:      "{{ item.gpgkey | default(omit) }}"
    proxy:       "{{ item.proxy | default(omit) }}"
    state:       "{{ item.state | default('present') }}"
  loop: >-
    {{
      rh8_base_repositories | default([]) 
      | union(rh8_product_repositories | default([]))
      | union(rh8_hosts_repositories | default([]))
    }}
  register: yum_register_rh8_all_repo_apt
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "8"
    - rh8_base_repositories is defined or
      rh8_product_repositories is defined or
      rh8_hosts_repositories is defined
  tags:
    - add_redhat_repo

# Redhat 9 repositories
- name: Configure repo yum <|> RedHat 9
  ansible.builtin.yum_repository:
    name:        "{{ item.name | default(item, true) }}"
    description: "{{ item.description | default(item.name, true) | default(item, true) }}"
    baseurl:     "{{ item.baseurl | default(omit) }}"
    enabled:     "{{ item.enabled | default(1) }}"
    exclude:     "{{ item.exclude | default(omit) }}"
    gpgcheck:    "{{ item.gpgcheck | default(0) }}"
    gpgkey:      "{{ item.gpgkey | default(omit) }}"
    proxy:       "{{ item.proxy | default(omit) }}"
    state:       "{{ item.state | default('present') }}"
  loop: >-
    {{
      rh9_base_repositories | default([]) 
      | union(rh9_product_repositories | default([]))
      | union(rh9_hosts_repositories | default([]))
    }}
  register: yum_register_rh9_all_repo
  when:
    - ansible_facts['distribution'] == "RedHat"
    - ansible_facts['distribution_major_version'] == "9"
    - rh9_base_repositories is defined or
      rh9_product_repositories is defined or
      rh9_hosts_repositories is defined
  tags:
    - add_redhat_repo