---

# Old format deb repositories Stable
- name: Configure repo apt old format <|> Debian Stable
  ansible.builtin.apt_repository:
    update_cache: False
    repo:     '{{ item.repo }}'
    codename: '{{ item.codename | default(omit) }}'
    filename: '{{ item.filename | regex_replace(".list$", "") | regex_replace(".sources$", "") }}'
    mode:     '{{ item.mode | default(omit) }}'
    state:    '{{ item.state | default("present") }}'
  loop: >-
    {{
      stable_apt_base_repositories | default([]) 
      | union(stable_product_repositories | default([]))
      | union(stable_hosts_repositories | default([]))
    }}
  register: apt_register_stable_all_repo
  when:
    - ansible_facts.distribution == "Debian" or
      ansible_facts.distribution == "Ubuntu"      ### Не очень уверен, возможно могут быть случаи, когда необходимо разделять stable репозитории на разные дистрибутивы
    - ansible_facts.distribution_major_version != "24"
    - stable_apt_base_repositories is defined or
      stable_product_repositories is defined or
      stable_hosts_repositories is defined
  tags: 
    - add_stable_repo
    - add_debian_repo
    - add_ubuntu_repo

# New format deb repositories Stable
- name: Configure repo Deb822 <|> Ubuntu Stable
  ansible.builtin.deb822_repository:
    allow_downgrade_to_insecure: '{{ item.allow_downgrade_to_insecure | default(omit) }}'
    allow_insecure:    '{{ item.allow_insecure | default(omit) }}'
    allow_weak:        '{{ item.allow_weak | default(omit) }}'
    architectures:     '{{ item.architectures | default(omit) }}'
    by_hash:           '{{ item.by_hash | default(omit) }}'
    check_date:        '{{ item.check_date | default(omit) }}'
    check_valid_until: '{{ item.check_valid_until | default(omit) }}'
    components:        '{{ item.components | default(omit) }}'
    data_max_future:   '{{ item.date_max_future | default(omit) }}'
    enabled:           '{{ item.enabled | default(omit) }}'
    inrelease_path:    '{{ item.inrelease_path | default(omit) }}'
    languages:         '{{ item.languages | default(omit) }}'
    name:              '{{ item.name }}'
    mode:              '{{ item.mode | default(omit) }}'
    pdiffs:            '{{ item.pdiffs | default(omit) }}'
    signed_by:         '{{ item.signed_by | default(omit) }}'
    state:             '{{ item.state | default("present") }}'
    suites:            '{{ item.suites | default(omit) }}'
    targets:           '{{ item.targets | default(omit) }}'
    trusted:           '{{ item.trusted | default(omit) }}'
    types:             '{{ item.types | default("deb") }}'
    uris:              '{{ item.uris }}'
  loop: >-
    {{
      stable_822_base_repositories | default([]) 
      | union(stable_822_product_repositories | default([]))
      | union(stable_822_hosts_repositories | default([]))
    }}
  register: apt_register_stable_822_all_repo
  when:
    - ansible_facts.distribution == "Ubuntu"
    - ansible_facts.distribution_major_version == "24"
    - stable_822_base_repositories is defined or
      stable_822_product_repositories is defined or
      stable_822_hosts_repositories is defined

- name: Update atp cache
  ansible.builtin.apt:
    update_cache: True
  when: apt_register_stable_822_all_repo.changed
  tags: 
    - add_stable_repo
    - add_ubuntu_repo


# Stable RPM repositories
- name: Configure repo yum <|> RPM stable repositories
  ansible.builtin.yum_repository:
    name:        "{{ item.name | default(item, true) | regex_replace('\\.repo$', '') }}"
    description: "{{ item.description | default(item.name, true) | default(item, true) }}"
    baseurl:     "{{ item.baseurl | default(omit) }}"
    enabled:     "{{ item.enabled | default(1) }}"
    exclude:     "{{ item.exclude | default(omit) }}"
    gpgcheck:    "{{ item.gpgcheck | default(0) }}"
    gpgkey:      "{{ item.gpgkey | default(omit) }}"
    proxy:       "{{ item.proxy | default(omit) }}"
    state:       "{{ item.state | default('present') }}"
  loop: >-
    {{
      stable_rpm_base_repositories | default([]) 
      | union(stable_rpm_product_repositories | default([]))
      | union(stable_rpm_hosts_repositories | default([]))
    }}
  register: yum_register_stable_all_repo
  when:
    - ansible_facts['distribution'] == "OracleLinux" or
      ansible_facts['distribution'] == "RedHat" or
      ansible_facts['distribution'] == "CentOS"
    - stable_rpm_base_repositories is defined or
      stable_rpm_product_repositories is defined or
      stable_rpm_hosts_repositories is defined
  tags: 
    - add_stable_repo
    - add_oracle_repo
    - add_redhat_repo
    - add_centos_repo